### ISSUE TITLE
Petscan no more working

### ISSUE THREAD

**Issue by wikimarcok** [magnusmanske/petscan_rs#141]
Blank (white) page at start, no error shown, from yesterday. Tried with Firefox and Chrome browsers (both up-to-date versions) on Ubuntu.

**Comment by M2k-dewiki** [comment]
Also see
* https://phabricator.wikimedia.org/T347311

**Comment by isaranto** [comment]
Hi! I am following up on this as this has been caused by a change in the underlying infrastructure that ORES is built upon.
ORES is being deprecated and the current ores-legacy application under ores.wikimedia.org does not support such callbacks, meaning that it will not return javascript objects but proper json. Such requests can be made as CORS is allowed for domains such as petscan.wmflabs.org.
@magnusmanske Would it be easy to use a fetch function instead with `https://ores.wikimedia.org/v3/scores/` and manipulate the json response?
let me know if I can help in any other way.

**Comment by magnusmanske** [comment]
Hi, just saw this issue. PetScan is back up, I deactivated the ORES functions until I can fix it properly.

**Comment by magnusmanske** [comment]
Fixed the request using `fetch`

**Comment by isaranto** [comment]
Thanks a lot @magnusmanske !
