### ISSUE TITLE
If you get a "400: Bad request" error, try properly encoding the URL

### ISSUE THREAD

**Issue by magnusmanske** [magnusmanske/petscan_rs#3]

**Comment by sjoerddebruin** [comment]
Is this related/caused by "®exp_filter" randomly appearing in fields?

**Comment by magnusmanske** [comment]
It might be related (I thought I fixed the "®exp_filter" thing), but mainly the underlying web server crate I use doesn't deal with raw "[" and "{" well. Example query?

**Comment by sjoerddebruin** [comment]
> It might be related (I thought I fixed the "®exp_filter" thing), but mainly the underlying web server crate I use doesn't deal with raw "[" and "{" well. Example query?

https://petscan.wmflabs.org/?language=en&project=wikipedia&ns%5B0%5D=1&sparql=select%20%3Fitem%20where%20%7B%0D%0A%09%3Fsitelink%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fnl.wikipedia.org%2F%3E%3B%20schema%3Aabout%20%3Fitem%20.%0D%0A%09%3Fitem%20wdt%3AP31%20wd%3AQ5%20.%0D%0A%09optional%20%7B%20%3Fitem%20wdt%3AP21%20%3Fgender%20.%20%7D%0D%0A%09filter%20%28%21bound%28%3Fgender%29%29%20.%0D%0A%7D&search_max_results=500&wikidata_label_language=nl&wikidata_prop_item_use=P21&wpiu=none&sortby=date&interface_language=en (which is also timing out since the upgrade)

**Comment by magnusmanske** [comment]
I have started #17 with your comment because it's a different issue

**Comment by magnusmanske** [comment]
I have replaced 'regexp_filter' with 'rxp_filter', which should prevent the issue. 'regexp_filter' is still supported for backwards compatibility.
