### ISSUE TITLE
Bad gateway on request.

### ISSUE THREAD

**Issue by tzachar** [magnusmanske/petscan_rs#74]
Hi.

I cannot make any requests to the petscan site.
Keep getting Bad Gateway errors.

Any change someone knows why?

**Comment by M2k-dewiki** [comment]
Hello,

the productive environment returns a "502 Bad Gateway" for same days now, for example:

https://petscan.wmflabs.org/?language=de&project=wikipedia&categories=Wikipedia:Artikel%20ohne%20Wikidata-Datenobjekt%0D%0A&negcats=Wikipedia%3AL%C3%B6schkandidat&combination=union&ns%5B0%5D=1&show_redirects=no&wikidata_item=without&interface_language=en&&doit=

while the development environment still returns the entries, for example:

https://petscan-dev.wmflabs.org/?language=de&project=wikipedia&categories=Wikipedia:Artikel%20ohne%20Wikidata-Datenobjekt%0D%0A&negcats=Wikipedia%3AL%C3%B6schkandidat&combination=union&ns%5B0%5D=1&show_redirects=no&wikidata_item=without&interface_language=en&&doit=

But, the development environment requires to log in ("Log into WiDaR to perform Wikidata edits"), which leads to 

https://tools.wmflabs.org/widar/index.php?action=authorize

which returns an error ("503 Service Unavailable" - "The URL you have requested, https://widar.toolforge.org/index.php?action=authorize, is not currently serviced.")

In my opion, the productive environment contains a newer program version of petscan, since this contains a link to "Quickstatements (2)" instead of a direct login for some time now. 

Would it be possible to update the development environment to the same program version as the productive enviroment?

Thanks a lot!

Kind regards,
M2k~dewiki

**Comment by M2k-dewiki** [comment]
Please also see

https://phabricator.wikimedia.org/T264758

https://bitbucket.org/magnusmanske/petscan/issues/163/petscans-down

**Comment by magnusmanske** [comment]
The "502 Bad Gateway" link you gave works in production at this time, I guess I fixed some other bug that fixed this as well. The dev environment is, well, for development, and I mostly develop from my own machine these days, so it hasn't been updated in a while.
